//----------------------------------------------------------
//                            Variables
//----------------------------------------------------------
import ImageAPI from "./bot-ai.js";
import { Client, Intents } from "discord.js";
//Tells these components to use the ai api file and discord.js respectively

const client = new Client({
  intents: [
    Intents.FLAGS.GUILDS,
    Intents.FLAGS.GUILD_MESSAGES,
    Intents.FLAGS.GUILD_VOICE_STATES,
  ],
});
//? Object ^^
//Declares intents for the bot (discord.js needs this for the bot to function) ^^
const TOKEN =
  "OTg0Mzg3MDU0MjQwNjY1NjEw.GqMjYj.lD4ubq3ndUds9O8FAwWdOI1D3B30p__Yzgwunw";
//Bot token (This is meant to be secret, obviously fine with teachers seeing it but don't go shouting it from rooftops xx)
//used to log into the bot like a password ^^
var greetingChoices = [
  "hey x",
  "how u doin",
  "yo",
  "ready 2 learn",
  "2 kool 4 skool",
  "birds are fake",
];
//Array of greetings for testing ^^
//? Array

let Greeting =
  greetingChoices[Math.floor(Math.random() * greetingChoices.length)];
//Variable to generate random greeting each run using math.random ^^
//? Selection

client.login(TOKEN);
//Bot login with bot token/password

//----------------------------------------------------------
//                            Login
//----------------------------------------------------------
client.on("ready", () => {
  console.log(`Logged in as ${client.user.tag}!`);
});
//When the bot is online, states its user tag to make sure it is correct & logged in
client.on("ready", () => {
  client.user.setActivity("despacito");
});
//? Function ?
//Sets the bot's status - just a little cosmetic thing :)
//----------------------------------------------------------
//                            Testing
//----------------------------------------------------------
client.on("messageCreate", (msg) => {
  if (msg.content === "ping") {
    msg.channel.send(Greeting);
  }
});
//Replies to 'ping' with a random result from the array 'Greeting' ^^

//----------------------------------------------------------
//                            Get URL
//----------------------------------------------------------

//Gets the URL of any uploaded attachment to a discord server (can be multiple)
client.on("messageCreate", (msg) => {
  msg.attachments.forEach(async (attachment) => {
    const url = attachment.url; //?Local Object
    console.log(url);

    if (url.includes(".webp")) {
      msg.channel.send("I can't read .webp files.");
      return;
    }
    //? Post-test?
    //----------------------------------------------------------
    //                 Alt Text Generator
    //----------------------------------------------------------

    const data = await ImageAPI.analyseImage(url);
    if (data?.description?.captions[0]?.text) {
      msg.channel.send(
        "**ALT TEXT:** This image is of " +
          data.description.captions[0].text +
          "."
      );
    }

    //Grabs the caption generated by Azure and sends it to discord
    if (data?.description?.tags?.length > 0) {
      const tags = data.description.tags;
      msg.channel.send("**Tags for this image are:** " + tags.join(", ") + ".");
      console.log(tags.join());
      //? JS Function (tags.join) ^^
    }
  });
  //Grabs the tags of the image which provide further description and sends it to discord
});

//----------------------------------------------------------
//                        Server Whitelist
//----------------------------------------------------------
const whitelist = ["993399791394508831", "939771378754801664"];
client.on("guildCreate", (guild) => {
  for (const item of whitelist) {
    console.log(item);
    if (item == guild.id) return;
    guild.leave();
  }
});
//? Loop (For loop)
//Uses a for loop to test every time the bot joins a new server and logs the whitelisted servers.
// If the server isn't whitelisted in this array, the bot will leave the server.

//----------------------------------------------------------
//                        Rubric Checklist
//----------------------------------------------------------
//* Commenting - Y
//* Variables - Y, both local and global
//* Functions - Y, discord.js specific and plain javascript (client.on is a discord.js function), (tags.join is a js function)
//* Logic Statements - Y - if statements
//* Arrays - Y - greeting / testing array as well as use of arrays of analysis data
//* Objects - Y - Used one specific to disord.js (Client intents) - local object?...
//* Looping - Y - For loop for whitelist
//* Control Structures - Y - if statements, for loop
//* Multiway Selection - Y - Math.random for greeting

//I have